name: Kotlin Lint Test

on:
  pull_request_review:
    types: [submitted]
  push:
    branches:
      - main

jobs:
  ktlint-lint:
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request_review' && github.event.review.state == 'approved') }}
    name: Run ktlintCheck
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Run ktlint (lint test)
        run: cd sdks/android && ./gradlew ktfmtCheck --quiet
